// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://hjwgcaaciaxdopakfenz.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqd2djYWFjaWF4ZG9wYWtmZW56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyNjAwMjcsImV4cCI6MjA0ODgzNjAyN30.7p5htIvDn452EaLcMGAGKzg7jsM227LuAv0Un89EJZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);